# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
numero = int(input('Digite um número: '))
print(f'A tabuada do número {numero} é:')
print(f'{numero} X  1 = {numero * 1:>2}')
print(f'{numero} X  2 = {numero * 2:>2}')
print(f'{numero} X  3 = {numero * 3:>2}')
print(f'{numero} X  4 = {numero * 4:>2}')
print(f'{numero} X  5 = {numero * 5:>2}')
print(f'{numero} X  6 = {numero * 6:>2}')
print(f'{numero} X  7 = {numero * 7:>2}')
print(f'{numero} X  8 = {numero * 8:>2}')
print(f'{numero} X  9 = {numero * 9:>2}')
print(f'{numero} X 10 = {numero * 10:>2}')
